# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master" ]
  
jobs:

  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: 
          mvn -B package --file pom.xml
       
      - name: List the current directory
        run: ls -a
      - name: What is there in the target folder
        run: |
          cd target
          ls -a


          
          
          







