name: Workflow1A

on:
  workflow_dispatch:
  workflow_call: 
  
jobs:
  Workflow1B:
    uses: Suheab1995/rock-paper-scissors/.github/workflows/Workflow1B.yml@master
  Workflow1C:
    uses: Suheab1995/rock-paper-scissors/.github/workflows/Workflow1C.yml@master

  Workflow1A:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
      - name: Run Script
        run: echo "hello worlld"
        
