name: Workflow2C

on:
  workflow_dispatch: 
  
jobs:

  Workflow2C:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
      - name: Run Script
        run: echo "hello worlld"
